version: '3.9'

services:
  app:
    image: btc/app
    build: .
    ports:
      - 1323:1323
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/
      DB_NAME: btc_billionare
    networks:
      - btc-network
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    networks:
      - btc-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - btc-network

networks:
  btc-network:
    driver: bridge